/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fysioSysteem.presentation;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fysioSysteem.businessLogic.behandeling.IBehandelCodeManager;
import fysioSysteem.businessLogic.behandeling.IBehandelingManager;
import fysioSysteem.businessLogic.behandeling.IKlantManager;
import fysioSysteem.domain.BehandelCode;
import fysioSysteem.domain.BehandelStatus;
import fysioSysteem.domain.Behandeling;
import fysioSysteem.domain.Klant;
import general.AppInjector;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;

/**
 *
 * @author Bert
 */
public class BehandelingEditPanel extends javax.swing.JPanel {

    /**
     * Creates new form BehandelingEditPanle
     */
    private IBehandelingManager behandelingManager;
    private IBehandelCodeManager behandelCodeManager;
    private IKlantManager klantManager;
    private Behandeling behandeling;

    /**
     * Creates new form BehandelingEditPanel
     */
    public BehandelingEditPanel() {
        Injector injector = Guice.createInjector(new AppInjector());
        behandelingManager = injector.getInstance(IBehandelingManager.class);
        behandelCodeManager = injector.getInstance(IBehandelCodeManager.class);
        klantManager = injector.getInstance(IKlantManager.class);

        initComponents();
    }

    public BehandelingEditPanel(Behandeling behandeling) {
        Injector injector = Guice.createInjector(new AppInjector());
        behandelingManager = injector.getInstance(IBehandelingManager.class);
        behandelCodeManager = injector.getInstance(IBehandelCodeManager.class);
        klantManager = injector.getInstance(IKlantManager.class);

        this.behandeling = behandeling;

        laadData();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblKlantBSN = new javax.swing.JLabel();
        cmbbxKlantBSN = new javax.swing.JComboBox();
        lblBehandelCode = new javax.swing.JLabel();
        txtBehandelCode = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        cmbbxStatus = new javax.swing.JComboBox();
        btnAnnuleren = new javax.swing.JButton();
        btnOpslaan = new javax.swing.JButton();

        lblKlantBSN.setText("Klant BSN");

        cmbbxKlantBSN.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblBehandelCode.setText("BehandelCode");

        lblStatus.setText("Status");

        cmbbxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAnnuleren.setText("Annuleren");
        btnAnnuleren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerenActionPerformed(evt);
            }
        });

        btnOpslaan.setText("Opslaan");
        btnOpslaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpslaanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbbxKlantBSN, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbbxStatus, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKlantBSN)
                            .addComponent(lblBehandelCode)
                            .addComponent(lblStatus))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtBehandelCode)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnnuleren)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOpslaan)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKlantBSN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbbxKlantBSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblBehandelCode)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBehandelCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnnuleren)
                    .addComponent(btnOpslaan))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnnulerenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerenActionPerformed
        HoofdVenster parent = (HoofdVenster) getParentFrame();
        parent.setPanel(new BehandelingOverzichtPanel());
    }//GEN-LAST:event_btnAnnulerenActionPerformed

    private void btnOpslaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpslaanActionPerformed
        JFrame frame = new JFrame();
        ArrayList<String> errorMessages = new ArrayList<String>();
        Border redBorder = BorderFactory.createLineBorder(Color.red);

        if (txtBehandelCode.getText().equals("")
                && txtBehandelCode.getText().length() >= 10) {

            txtBehandelCode.setBorder(redBorder);
            errorMessages.add("- Behandelcode is incorrect");
        }

        if (cmbbxKlantBSN.getSelectedItem().toString() == "") {
            cmbbxKlantBSN.setBorder(redBorder);
            errorMessages.add("- Behandelcode is incorrect");
        }

        if (cmbbxStatus.getSelectedItem().toString() == "") {
            cmbbxStatus.setBorder(redBorder);
            errorMessages.add("- Status is incorrect");
        }

        if (errorMessages.size() < 1) {
            BehandelCode behandelCode = behandelCodeManager.getBehandelCode(Integer.parseInt(txtBehandelCode.getText()));
            Klant klant = klantManager.getKlant(cmbbxKlantBSN.getSelectedItem().toString());

            if (behandeling != null) {
                Behandeling newBehandeling = new Behandeling(behandeling.getId(), BehandelStatus.valueOf(cmbbxStatus.getSelectedItem().toString()), klant, behandelCode);
                behandelingManager.setBehandeling(newBehandeling);
            } else {
                Behandeling newBehandeling = new Behandeling(BehandelStatus.valueOf(cmbbxStatus.getSelectedItem().toString()), klant, behandelCode);
                behandelingManager.addBehandeling(newBehandeling);
            }

            revalidate();
            repaint();

            JOptionPane.showMessageDialog(frame, "De behandelinggegevens zijn succesvol opgeslagen.");
        } else {
            int sizeStringBuilder = errorMessages.size() + 1;
            StringBuilder builder = new StringBuilder(sizeStringBuilder);
            builder.append("Controleer de volgende velden op volledigheid en correctheid:" + "\n");

            for (String s : errorMessages) {
                builder.append(s + "\n");
            }

            JOptionPane.showMessageDialog(null, builder.toString());
        }
    }//GEN-LAST:event_btnOpslaanActionPerformed

    private void laadData() {
        cmbbxKlantBSN.setSelectedItem(behandeling.getKlant().getBsn());
        txtBehandelCode.setText(Integer.toString(behandeling.getBehandelCode().getCode()));
        cmbbxStatus.setSelectedItem(behandeling.getStatus());
    }

    private JFrame getParentFrame() {
        return (JFrame) SwingUtilities.getRoot(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuleren;
    private javax.swing.JButton btnOpslaan;
    private javax.swing.JComboBox cmbbxKlantBSN;
    private javax.swing.JComboBox cmbbxStatus;
    private javax.swing.JLabel lblBehandelCode;
    private javax.swing.JLabel lblKlantBSN;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtBehandelCode;
    // End of variables declaration//GEN-END:variables
}
