/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fysioSysteem.presentation;

import com.google.inject.Guice;
import com.google.inject.Injector;

import fysioSysteem.businessLogic.behandeling.IBehandelCodeManager;
import fysioSysteem.domain.BehandelCode;
import general.AppInjector;

import java.awt.Color;
import java.util.ArrayList;

import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;


/**
 *
 * @author Bob
 */
public class BehandelCodeEditPanel extends javax.swing.JPanel {
	
	private IBehandelCodeManager behandelCodeManager;
	
	
    /**
     * Creates new form BehandelCodeEditPanel
     */
    public BehandelCodeEditPanel() {
        initComponents();
    }
    
    private JFrame getParentFrame() {
        return (JFrame) SwingUtilities.getRoot(this);
    }

    private boolean controleerVelden(){
    	ArrayList<String> errorMessages = new ArrayList<>();
        Border redBorder = BorderFactory.createLineBorder(Color.red);
    	
    	//CODEVELD
	    	boolean tempcode = true;
	    	
	    	try{
	    		Integer.parseInt(txtCode.getText());
	    	}
	    	catch(NumberFormatException e){
	    		tempcode = false;
	    	}
	    	
	    	if (txtCode.getText().isEmpty()
	    		|| txtCode.getText().length() >= 15
	    		|| tempcode == false){
	    			
	    			txtCode.setBorder(redBorder);
	    			errorMessages.add("- Codeveld");
	    	}
	    	
	    //NAAMVELD
	    	
	    	if (txtNaam.getText().isEmpty()
	    		||txtNaam.getText().length() >= 50){
	    			
	    		txtNaam.setBorder(redBorder);
	    		errorMessages.add("- Naamveld");
	    		}
	    	
	    //AANTAL SESSIES
	    	
	    	boolean tempsessies = true;
	    	int sessiestemp = 0;
	    	
	    	try{
	    		sessiestemp = (Integer) spnAantalSessies.getValue();
	    	}
	    	catch(NumberFormatException e){
	    		tempsessies = false;
	    	}
	    	
	    	if (sessiestemp !=0 || tempsessies == false){
	    		
	    		spnAantalSessies.setBorder(redBorder);
	    		errorMessages.add("- Aantal Sessies");
	    	}
	    	
	    //DURATIE SESSIE
	    	
	    	boolean tempduratie = true;
	    	int duratietemp = 0;
	    	
	    	try{
	    		duratietemp = (Integer) spnDuratieSessie.getValue();
	    	}
	    	catch(NumberFormatException e){
	    		tempsessies = false;
	    	}
	    	
	    	if (duratietemp !=0 || tempduratie == false){
	    		
	    		spnDuratieSessie.setBorder(redBorder);
	    		errorMessages.add("- Aantal Sessies");
	    	}
	    	
	    //TARIEF
	    	
	    	boolean temptarief = true;
	    	
	    	try{
	    		Double.parseDouble(txtTarief.getText());
	    	}
	    	catch(NumberFormatException e){
	    		temptarief = false;
	    	}
	    	
	    	if (txtTarief.getText().isEmpty()
	    			|| temptarief == false)
	    	{
    			txtTarief.setBorder(redBorder);
	    		errorMessages.add("- Tarief");
	    	}
	    		
	    	
	    if (errorMessages.size() ==0){
	    	return true;
	    }
	    else{
	    	return false;
	    }
	    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNaam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        spnAantalSessies = new javax.swing.JSpinner();
        spnDuratieSessie = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnOpslaan = new javax.swing.JButton();
        btnAnnuleren = new javax.swing.JButton();
        txtTarief = new javax.swing.JTextField();

        jLabel1.setText("Behandelcode");

        jLabel2.setText("Behandelingnaam");

        jLabel3.setText("Aantal sessies");

        jLabel4.setText("Duratie sessie");

        jLabel5.setText("Tarief");

        btnOpslaan.setText("Opslaan");

        btnAnnuleren.setText("Annuleren");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTarief)
                    .addComponent(txtCode)
                    .addComponent(txtNaam)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAnnuleren)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOpslaan))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spnAantalSessies, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(spnDuratieSessie, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnAantalSessies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnDuratieSessie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTarief, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOpslaan)
                    .addComponent(btnAnnuleren))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpslaanActionPerformed(java.awt.event.ActionEvent evt){
    	
    	if (controleerVelden()==true){
        	int code = Integer.parseInt(txtCode.getText());
        	int sessies = (Integer) spnAantalSessies.getValue();
        	int duur = (Integer) spnDuratieSessie.getValue();
        	double tarief = Double.parseDouble(txtTarief.getText());
        	BehandelCode behandelcode = new BehandelCode(code,sessies,txtNaam.getText(),duur,tarief);

        	behandelCodeManager.addBehandelCode(behandelcode);
    	}
    	

    }
    
    private void btnAnnulerenActionPerformed(java.awt.event.ActionEvent evt){
        HoofdVenster parent = (HoofdVenster) getParentFrame();
        Injector injector = Guice.createInjector(new AppInjector());
        parent.setPanel(injector.getInstance(MedewerkerOverzichtPanel.class));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuleren;
    private javax.swing.JButton btnOpslaan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner spnAantalSessies;
    private javax.swing.JSpinner spnDuratieSessie;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtNaam;
    private javax.swing.JTextField txtTarief;
    // End of variables declaration//GEN-END:variables
}
