/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fysioSysteem.presentation;

import com.google.inject.Inject;
import fysioSysteem.businessLogic.behandeling.IBehandelingManager;
import fysioSysteem.domain.Behandeling;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bert
 */
public class BehandelingOverzichtPanel extends javax.swing.JPanel {

    private IBehandelingManager behandelingManager;

    private ArrayList<Behandeling> behandelingen;

    /**
     * Creates new form BehandelOverzichtPanel
     */
    @Inject
    public BehandelingOverzichtPanel(IBehandelingManager behandelingManager) {
        this.behandelingManager = behandelingManager;

        this.behandelingen = behandelingManager.getBehandelingen();
        
        initComponents();
        laadData();
    }

    private void laadData() {
        DefaultTableModel mdl = new DefaultTableModel(
            new Object[]{"ID", "Klant BSN", "BehandelCode", "Status"}, 0) {

                // Tabel Bewerken uit
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

        for (Behandeling b : behandelingen) {
            mdl.addRow(new Object[]{
                b.getId(),
                b.getKlant().getBsn(),
                b.getBehandelCode().getCode(),
                b.getStatus()
            });
        }

        tblBehandelingen.setModel(mdl);
    }
    
    private JFrame getParentFrame() {
        return (JFrame) SwingUtilities.getRoot(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnWijzigen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBehandelingen = new javax.swing.JTable();

        btnWijzigen.setText("Behandeling Wijzigen");
        btnWijzigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWijzigenActionPerformed(evt);
            }
        });

        tblBehandelingen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBehandelingen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnWijzigen)
                .addContainerGap(505, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(358, Short.MAX_VALUE)
                .addComponent(btnWijzigen)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                    .addGap(45, 45, 45)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnWijzigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWijzigenActionPerformed
        try {
            Behandeling b = behandelingen.get(
                    tblBehandelingen.convertRowIndexToModel(tblBehandelingen.getSelectedRow()));

            HoofdVenster parent = (HoofdVenster) getParentFrame();
            parent.setPanel(new BehandelingEditPanel(b));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Selecteer een rij, alstublieft.");
        }
    }//GEN-LAST:event_btnWijzigenActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnWijzigen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBehandelingen;
    // End of variables declaration//GEN-END:variables
}
