/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fysioSysteem.presentation;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fysioSysteem.businessLogic.behandeling.IBehandelingManager;
import fysioSysteem.domain.Behandeling;
import general.AppInjector;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bert
 */
public class BehandelingOverzichtPanel extends javax.swing.JPanel {

    private IBehandelingManager behandelingManager;

    private ArrayList<Behandeling> behandelingen;

    /**
     * Creates new form BehandelOverzichtPanel
     */
    public BehandelingOverzichtPanel() {
        Injector injector = Guice.createInjector(new AppInjector());
        this.behandelingManager = injector.getInstance(IBehandelingManager.class);
        
        initComponents();
        laadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnToevoegen = new javax.swing.JButton();
        btnWijzigen = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBehandelingen = new javax.swing.JTable();

        btnToevoegen.setText("Behandeling Toevoegen");
        btnToevoegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToevoegenActionPerformed(evt);
            }
        });

        btnWijzigen.setText("Behandeling Wijzigen");
        btnWijzigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWijzigenActionPerformed(evt);
            }
        });

        tblBehandelingen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBehandelingen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 648, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnToevoegen)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnWijzigen)
                            .addGap(338, 338, 338)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnToevoegen)
                        .addComponent(btnWijzigen))
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnToevoegenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToevoegenActionPerformed
        HoofdVenster parent = (HoofdVenster) getParentFrame();
        parent.setPanel(new BehandelingEditPanel());
    }//GEN-LAST:event_btnToevoegenActionPerformed

    private void btnWijzigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWijzigenActionPerformed
        try {
            Behandeling b = behandelingen.get(
                    tblBehandelingen.convertRowIndexToModel(tblBehandelingen.getSelectedRow()));

            HoofdVenster parent = (HoofdVenster) getParentFrame();
            parent.setPanel(new BehandelingEditPanel(b));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Selecteer een rij, alstublieft.");
        }
    }//GEN-LAST:event_btnWijzigenActionPerformed

    private JFrame getParentFrame() {
        return (JFrame) SwingUtilities.getRoot(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnToevoegen;
    private javax.swing.JButton btnWijzigen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBehandelingen;
    // End of variables declaration//GEN-END:variables

    private void laadData() {
        ArrayList<Behandeling> behandelingen = this.behandelingManager.getBehandelingen();

        DefaultTableModel mdl = new DefaultTableModel(
                new Object[]{"ID", "Klant BSN", "BehandelCode", "Status"}, 0) {

                    // Tabel Bewerken uit
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false;
                    }
                };

        for (Behandeling b : behandelingen) {
            mdl.addRow(new Object[]{
                b.getId(),
                b.getKlant().getBsn(),
                b.getBehandelCode().getCode(),
                b.getStatus()
            });
        }

        tblBehandelingen.setModel(mdl);
    }
}
