/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fysioSysteem.presentation;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fysioSysteem.businessLogic.behandeling.IDiagnoseManager;
import fysioSysteem.domain.Diagnose;
import fysioSysteem.domain.Klant;
import general.AppInjector;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Bob
 */
public class DiagnoseOverzichtPanel extends javax.swing.JPanel {

    private IDiagnoseManager diagnoseManager;
    
    private Klant klant;
    private ArrayList<Diagnose> diagnoses;
    private Diagnose diagnose = null;
    
    /**
     * Creates new form DiagnoseOverzichtPanel
     */
    public DiagnoseOverzichtPanel(Klant k) {
        Injector injector = Guice.createInjector(new AppInjector());
        diagnoseManager = injector.getInstance(IDiagnoseManager.class);
        
        klant = k;
        diagnoses = k.getDiagnoses();
        
        initComponents();
        laadData();
    }
    
    private void laadData() {
        DefaultComboBoxModel<Diagnose> diagnoseModel
                = new DefaultComboBoxModel<>();
        
        for (Diagnose d : diagnoses) {
            diagnoseModel.addElement(d);
        }
        
        cbDiagnose.setModel(diagnoseModel);
        
        if(diagnoses.size() > 0)
            setDiagnose(diagnoses.get(0));
    }
    
    private void setDiagnose(Diagnose d) {
        diagnose = d;
        
        if(d != null) {
            txtCode.setText(Integer.toString(d.getCode()));
            txtOmschrijving.setText(d.getOmschrijving());
        }
        else {
            txtCode.setText("");
            txtOmschrijving.setText("");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        txtOmschrijving = new javax.swing.JTextArea();
        btnOpslaan = new javax.swing.JButton();
        btnSluiten = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbDiagnose = new javax.swing.JComboBox();
        btnLaadDiagnose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        btnNieuw = new javax.swing.JButton();

        txtOmschrijving.setColumns(20);
        txtOmschrijving.setRows(5);
        jScrollPane2.setViewportView(txtOmschrijving);

        btnOpslaan.setText("Opslaan");
        btnOpslaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpslaanActionPerformed(evt);
            }
        });

        btnSluiten.setText("Sluiten");

        jLabel1.setText("Diagnoses");

        btnLaadDiagnose.setText("Open");
        btnLaadDiagnose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaadDiagnoseActionPerformed(evt);
            }
        });

        jLabel2.setText("Diagnose");

        txtCode.setEditable(false);

        btnNieuw.setText("Nieuw");
        btnNieuw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNieuwActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSluiten)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOpslaan))
                    .addComponent(txtCode)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbDiagnose, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLaadDiagnose)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNieuw)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbDiagnose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLaadDiagnose)
                    .addComponent(btnNieuw))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSluiten)
                    .addComponent(btnOpslaan))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLaadDiagnoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaadDiagnoseActionPerformed
        Diagnose d = diagnoses.get(cbDiagnose.getSelectedIndex());
        setDiagnose(d);
    }//GEN-LAST:event_btnLaadDiagnoseActionPerformed

    private void btnNieuwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNieuwActionPerformed
        setDiagnose(null);
    }//GEN-LAST:event_btnNieuwActionPerformed

    private void btnOpslaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpslaanActionPerformed
       if(diagnose != null) { // Wijzigen
            diagnose.setOmschrijving(txtOmschrijving.getText());
            diagnose.setKlant(klant);
            
            diagnoseManager.setDiagnose(diagnose);
        }
        else { // Toevoegen
            diagnoseManager.addDiagnose(new Diagnose(
                    txtOmschrijving.getText(),
                    klant
            ));
        }
    }//GEN-LAST:event_btnOpslaanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaadDiagnose;
    private javax.swing.JButton btnNieuw;
    private javax.swing.JButton btnOpslaan;
    private javax.swing.JButton btnSluiten;
    private javax.swing.JComboBox cbDiagnose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextArea txtOmschrijving;
    // End of variables declaration//GEN-END:variables
}
