/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fysioSysteem.presentation;

import com.google.inject.Guice;
import com.google.inject.Inject;
import com.google.inject.Injector;
import fysioSysteem.businessLogic.behandeling.IKlantManager;
import fysioSysteem.domain.Klant;
import general.AppInjector;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bob
 */
public class KlantOverzichtPanel extends javax.swing.JPanel {

    private IKlantManager klantenManager;
    
    private ArrayList<Klant> klanten;
    
    /**
     * Creates new form KlantOverzichtPanel
     * @param klantenManager
     */
    @Inject
    public KlantOverzichtPanel(IKlantManager klantenManager) {
        this.klantenManager = klantenManager;
        
        klanten = klantenManager.getKlanten();
        
        initComponents();
        laadData();
    }
    
    private void laadData() {
        DefaultTableModel klantModel = new DefaultTableModel(
                new Object[]{"BSN", "Naam"}, 0
        );
        
        for (Klant k : klanten) {
            klantModel.addRow(new Object[]{
                k.getBsn(), k.getNaam()
            });
        }

        tblKlanten.setModel(klantModel);
    }
    
    private JFrame getParentFrame() {
        return (JFrame) SwingUtilities.getRoot(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKlanten = new javax.swing.JTable();
        btnKlantgegevens = new javax.swing.JButton();

        tblKlanten.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKlanten);

        btnKlantgegevens.setText("Open klantgegevens");
        btnKlantgegevens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKlantgegevensActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 531, Short.MAX_VALUE)
                        .addComponent(btnKlantgegevens))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnKlantgegevens)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnKlantgegevensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKlantgegevensActionPerformed
        Klant k = klanten.get(
            tblKlanten.convertRowIndexToModel(tblKlanten.getSelectedRow()));
        
        HoofdVenster parent = (HoofdVenster) getParentFrame();
        parent.setPanel(new KlantEditPanel(k));
    }//GEN-LAST:event_btnKlantgegevensActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKlantgegevens;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblKlanten;
    // End of variables declaration//GEN-END:variables
}
