/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fysioSysteem.presentation;

import com.google.inject.Inject;
import fysioSysteem.businessLogic.login.ILoginManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Bob
 */
public class LoginVenster extends javax.swing.JFrame {

    private ILoginManager lgn;

    /**
     * Creates new form LoginVenster
     */
    @Inject
    public LoginVenster(ILoginManager lgn) {

        this.lgn = lgn;

        initComponents();        
        getRootPane().setDefaultButton(btnInloggen);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtGebruikersnaam = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAnnuleren = new javax.swing.JButton();
        btnInloggen = new javax.swing.JButton();
        txtWachtwoord = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FysioSysteem - Inloggen");
        setResizable(false);

        jLabel1.setText("Medewerker ID");

        txtGebruikersnaam.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel2.setText("Wachtwoord");

        btnAnnuleren.setText("Annuleren");
        btnAnnuleren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerenActionPerformed(evt);
            }
        });

        btnInloggen.setText("Inloggen");
        btnInloggen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInloggenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtWachtwoord)
                    .addComponent(txtGebruikersnaam)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnnuleren)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                        .addComponent(btnInloggen))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGebruikersnaam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtWachtwoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnnuleren)
                    .addComponent(btnInloggen))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInloggenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInloggenActionPerformed
        int medewerkerId = Integer.parseInt(txtGebruikersnaam.getText());
        String medewerkerPass = new String(txtWachtwoord.getPassword());
        if (lgn.isActief(medewerkerId)) {
            if (lgn.valideer(medewerkerId, medewerkerPass)) {
                LoginVenster.this.dispose();
                new HoofdVenster().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(LoginVenster.this,
                        "Ongeldige gebruikersnaam of wachtwoord",
                        "Validatie error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(LoginVenster.this,
                    "Deze gebruiker is in actief.",
                    "Validatie error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnInloggenActionPerformed

    private void btnAnnulerenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerenActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnAnnulerenActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuleren;
    private javax.swing.JButton btnInloggen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtGebruikersnaam;
    private javax.swing.JPasswordField txtWachtwoord;
    // End of variables declaration//GEN-END:variables
}
